name: Build wcap

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main, master]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x64, arm64]  # 同时构建 x64 和 arm64 版本

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '17.0'  # VS 2022

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
          build.cmd ${{ matrix.arch }} release
          dir *.exe  # 验证生成文件

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wcap-${{ matrix.arch }}.exe
          path: wcap-${{ matrix.arch }}.exe
